services:
  backend:
    build:
      context: .
      dockerfile: Dockerfile.dev
    ports:
      - '8080:8080'
    environment:
      - NODE_ENV=production
      - JWT_SECRET=${JWT_SECRET}
      - PORT=${PORT:-8080}
      - DATABASE_URL=${DATABASE_URL}
    restart: unless-stopped
    healthcheck:
      test:
        [
          'CMD',
          'wget',
          '--no-verbose',
          '--tries=1',
          '--spider',
          'http://localhost:8080/health',
        ]
      interval: 30s
      timeout: 30s
      retries: 3
      start_period: 10s
    # Optional: Add resource limits for Azure Container Instances
    deploy:
      resources:
        limits:
          memory: 512M
        reservations:
          memory: 256M
